import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const places = [
  // ── HERITAGE (10) ──────────────────────────────────────────
  {
    name: "Shaniwar Wada",
    emoji: "🏰",
    category: "Heritage",
    rating: 4.6,
    latitude: 18.5194,
    longitude: 73.8553,
    entryFee: "₹25",
    estYear: "1732",
    visitTime: "2h",
    hours: "8:00 AM – 6:30 PM",
    phone: "020 2444 5051",
    address: "Shaniwar Peth",
    accessible: true,
    guidedTours: true,
    tag: "Must Visit",
    tagColor: "terracotta",
    bgColor: "#F2EAE7",
    description: "The historic seat of the Peshwas of the Maratha Empire.",
    distance: "Calculating...",
  },
  {
    name: "Aga Khan Palace",
    emoji: "🏛️",
    category: "Heritage",
    rating: 4.5,
    latitude: 18.5523,
    longitude: 73.9015,
    entryFee: "₹30",
    estYear: "1892",
    visitTime: "1.5h",
    hours: "9:00 AM – 5:30 PM",
    phone: "020 2668 0250",
    address: "Yerwada",
    accessible: true,
    guidedTours: true,
    tag: "Historic",
    tagColor: "terracotta",
    bgColor: "#F2EAE7",
    description: "Built by Sultan Muhammed Shah Aga Khan III in 1892.",
    distance: "Calculating...",
  },
  {
    name: "Pataleshwar Caves",
    emoji: "🕳️",
    category: "Heritage",
    rating: 4.4,
    latitude: 18.5265,
    longitude: 73.8504,
    entryFee: "Free",
    estYear: "8th Century",
    visitTime: "1h",
    hours: "8:00 AM – 5:30 PM",
    phone: "—",
    address: "Jangli Maharaj Road",
    accessible: false,
    guidedTours: false,
    tag: "Ancient",
    tagColor: "terracotta",
    bgColor: "#F2EAE7",
    description: "8th-century rock-cut cave temple dedicated to Lord Shiva.",
    distance: "Calculating...",
  },
  {
    name: "Raja Dinkar Kelkar Museum",
    emoji: "🏺",
    category: "Heritage",
    rating: 4.6,
    latitude: 18.5108,
    longitude: 73.8542,
    entryFee: "₹100",
    estYear: "1962",
    visitTime: "2.5h",
    hours: "10:00 AM – 5:30 PM",
    phone: "020 2447 4466",
    address: "Shukrawar Peth",
    accessible: true,
    guidedTours: true,
    tag: "Cultural",
    tagColor: "terracotta",
    bgColor: "#F2EAE7",
    description: "One-man collection of over 21,000 artifacts.",
    distance: "Calculating...",
  },
  {
    name: "Vishrambaug Wada",
    emoji: "🏘️",
    category: "Heritage",
    rating: 4.3,
    latitude: 18.5135,
    longitude: 73.8545,
    entryFee: "Free",
    estYear: "1807",
    visitTime: "1h",
    hours: "10:00 AM – 5:00 PM",
    phone: "—",
    address: "Sadashiv Peth",
    accessible: true,
    guidedTours: false,
    tag: "Mansion",
    tagColor: "terracotta",
    bgColor: "#F2EAE7",
    description: "A fine example of Maratha architecture built by Peshwa Bajirao II.",
    distance: "Calculating...",
  },
  {
    name: "Lal Mahal",
    emoji: "🏮",
    category: "Heritage",
    rating: 4.4,
    latitude: 18.52,
    longitude: 73.8558,
    entryFee: "₹5",
    estYear: "1630",
    visitTime: "45 min",
    hours: "9:00 AM – 1:00 PM, 4:00 PM – 8:00 PM",
    phone: "—",
    address: "Kasba Peth",
    accessible: true,
    guidedTours: false,
    tag: "Shivaji Maharaj",
    tagColor: "terracotta",
    bgColor: "#F2EAE7",
    description: "Red brick palace where Chhatrapati Shivaji Maharaj spent his childhood.",
    distance: "Calculating...",
  },
  {
    name: "Shinde Chhatri",
    emoji: "🕌",
    category: "Heritage",
    rating: 4.5,
    latitude: 18.4908,
    longitude: 73.8967,
    entryFee: "₹20",
    estYear: "18th Century",
    visitTime: "1h",
    hours: "9:00 AM – 6:00 PM",
    phone: "—",
    address: "Wanowrie",
    accessible: true,
    guidedTours: false,
    tag: "Architecture",
    tagColor: "terracotta",
    bgColor: "#F2EAE7",
    description: "Memorial dedicated to the 18th-century Maratha leader Mahadji Shinde.",
    distance: "Calculating...",
  },
  {
    name: "Nana Wada",
    emoji: "🏛️",
    category: "Heritage",
    rating: 4.2,
    latitude: 18.518,
    longitude: 73.8545,
    entryFee: "Free",
    estYear: "1780",
    visitTime: "45 min",
    hours: "10:00 AM – 5:00 PM",
    phone: "—",
    address: "Shaniwar Peth",
    accessible: true,
    guidedTours: false,
    tag: "Historic",
    tagColor: "terracotta",
    bgColor: "#F2EAE7",
    description: "Built by Nana Phadnavis, the chief administrator of the Peshwas.",
    distance: "Calculating...",
  },
  {
    name: "Mahatma Phule Museum",
    emoji: "🖼️",
    category: "Heritage",
    rating: 4.1,
    latitude: 18.524,
    longitude: 73.847,
    entryFee: "₹10",
    estYear: "1890",
    visitTime: "1.5h",
    hours: "9:00 AM – 5:00 PM",
    phone: "—",
    address: "Shivajinagar",
    accessible: true,
    guidedTours: false,
    tag: "Knowledge",
    tagColor: "terracotta",
    bgColor: "#F2EAE7",
    description: "Houses industrial and agricultural exhibits.",
    distance: "Calculating...",
  },
  {
    name: "Tribal Museum",
    emoji: "🏹",
    category: "Heritage",
    rating: 4.3,
    latitude: 18.528,
    longitude: 73.882,
    entryFee: "₹20",
    estYear: "1962",
    visitTime: "1.5h",
    hours: "10:30 AM – 5:30 PM",
    phone: "—",
    address: "Koregaon Park",
    accessible: true,
    guidedTours: true,
    tag: "Tribal Art",
    tagColor: "terracotta",
    bgColor: "#F2EAE7",
    description: "Exhibits artifacts from the tribal communities of Maharashtra.",
    distance: "Calculating...",
  },

  // ── TEMPLES (10) ──────────────────────────────────────────
  {
    name: "Dagdusheth Halwai Ganpati",
    emoji: "⛩️",
    category: "Temple",
    rating: 4.9,
    latitude: 18.5164,
    longitude: 73.856,
    entryFee: "Free",
    estYear: "1893",
    visitTime: "45 min",
    hours: "6:00 AM – 10:30 PM",
    phone: "020 2447 9999",
    address: "Budhwar Peth",
    accessible: true,
    guidedTours: false,
    tag: "Iconic",
    tagColor: "amber",
    bgColor: "#FDF3E0",
    description: "The most famous Ganesh temple in Pune.",
    distance: "Calculating...",
  },
  {
    name: "Parvati Temple",
    emoji: "⛰️",
    category: "Temple",
    rating: 4.8,
    latitude: 18.4984,
    longitude: 73.8445,
    entryFee: "Free",
    estYear: "1749",
    visitTime: "1.5h",
    hours: "5:00 AM – 8:00 PM",
    phone: "—",
    address: "Parvati Hill",
    accessible: false,
    guidedTours: false,
    tag: "Viewpoint",
    tagColor: "amber",
    bgColor: "#FDF3E0",
    description: "Hilltop temple complex with a panoramic view of the city.",
    distance: "Calculating...",
  },
  {
    name: "Chaturshringi Temple",
    emoji: "🌺",
    category: "Temple",
    rating: 4.7,
    latitude: 18.5366,
    longitude: 73.8285,
    entryFee: "Free",
    estYear: "8th Century",
    visitTime: "1h",
    hours: "6:00 AM – 9:00 PM",
    phone: "—",
    address: "Senapati Bapat Road",
    accessible: true,
    guidedTours: false,
    tag: "Ancient",
    tagColor: "amber",
    bgColor: "#FDF3E0",
    description: "Temple dedicated to Goddess Chaturshringi.",
    distance: "Calculating...",
  },
  {
    name: "Kasba Ganpati",
    emoji: "🕉️",
    category: "Temple",
    rating: 4.7,
    latitude: 18.5204,
    longitude: 73.857,
    entryFee: "Free",
    estYear: "1630",
    visitTime: "30 min",
    hours: "6:00 AM – 10:00 PM",
    phone: "—",
    address: "Kasba Peth",
    accessible: true,
    guidedTours: false,
    tag: "First Deity",
    tagColor: "amber",
    bgColor: "#FDF3E0",
    description: "The first deity (Gramadevata) of Pune.",
    distance: "Calculating...",
  },
  {
    name: "Saras Baug Ganpati",
    emoji: "🛶",
    category: "Temple",
    rating: 4.6,
    latitude: 18.5005,
    longitude: 73.8525,
    entryFee: "Free",
    estYear: "1784",
    visitTime: "1h",
    hours: "6:00 AM – 9:00 PM",
    phone: "—",
    address: "Saras Baug",
    accessible: true,
    guidedTours: false,
    tag: "Island Temple",
    tagColor: "amber",
    bgColor: "#FDF3E0",
    description: "Beautiful temple located in a lake setting.",
    distance: "Calculating...",
  },
  {
    name: "Omkareshwar Temple",
    emoji: "🔱",
    category: "Temple",
    rating: 4.5,
    latitude: 18.5218,
    longitude: 73.8495,
    entryFee: "Free",
    estYear: "1738",
    visitTime: "45 min",
    hours: "6:00 AM – 9:00 PM",
    phone: "—",
    address: "Shaniwar Peth",
    accessible: true,
    guidedTours: false,
    tag: "Peshwa Era",
    tagColor: "amber",
    bgColor: "#FDF3E0",
    description: "Ancient Shiva temple on the banks of Mutha river.",
    distance: "Calculating...",
  },
  {
    name: "ISKCON NVCC",
    emoji: "🛕",
    category: "Temple",
    rating: 4.9,
    latitude: 18.4518,
    longitude: 73.882,
    entryFee: "Free",
    estYear: "2013",
    visitTime: "2h",
    hours: "4:30 AM – 9:00 PM",
    phone: "020 4103 3200",
    address: "Katraj-Kondhwa Road",
    accessible: true,
    guidedTours: true,
    tag: "Spiritual",
    tagColor: "amber",
    bgColor: "#FDF3E0",
    description: "Sprawling spiritual complex and temple.",
    distance: "Calculating...",
  },
  {
    name: "Jangali Maharaj Temple",
    emoji: "🧘",
    category: "Temple",
    rating: 4.6,
    latitude: 18.526,
    longitude: 73.8505,
    entryFee: "Free",
    estYear: "1890",
    visitTime: "45 min",
    hours: "6:00 AM – 9:00 PM",
    phone: "—",
    address: "JM Road",
    accessible: true,
    guidedTours: false,
    tag: "Serene",
    tagColor: "amber",
    bgColor: "#FDF3E0",
    description: "Dedicated to the saint Sadguru Jangali Maharaj.",
    distance: "Calculating...",
  },
  {
    name: "Mahalakshmi Temple",
    emoji: "💰",
    category: "Temple",
    rating: 4.7,
    latitude: 18.514,
    longitude: 73.855,
    entryFee: "Free",
    estYear: "—",
    visitTime: "30 min",
    hours: "6:00 AM – 10:00 PM",
    phone: "—",
    address: "Saras Baug",
    accessible: true,
    guidedTours: false,
    tag: "Prosperity",
    tagColor: "amber",
    bgColor: "#FDF3E0",
    description: "Beautiful temple dedicated to Goddess Mahalakshmi.",
    distance: "Calculating...",
  },
  {
    name: "Someshwar Wadi Temple",
    emoji: "🌊",
    category: "Temple",
    rating: 4.4,
    latitude: 18.556,
    longitude: 73.811,
    entryFee: "Free",
    estYear: "—",
    visitTime: "45 min",
    hours: "6:00 AM – 8:00 PM",
    phone: "—",
    address: "Baner Pashan Road",
    accessible: true,
    guidedTours: false,
    tag: "Nature Mix",
    tagColor: "amber",
    bgColor: "#FDF3E0",
    description: "Peaceful Shiva temple with a stream nearby.",
    distance: "Calculating...",
  },

  // ── NATURE (10) ──────────────────────────────────────────
  {
    name: "Vetal Tekdi",
    emoji: "🥾",
    category: "Nature",
    rating: 4.7,
    latitude: 18.5275,
    longitude: 73.8242,
    entryFee: "Free",
    estYear: "—",
    visitTime: "2.5h",
    hours: "Always open",
    phone: "—",
    address: "Kothrud/Pashan",
    accessible: false,
    guidedTours: false,
    tag: "Highest Point",
    tagColor: "sage",
    bgColor: "#EBF0E8",
    description: "The highest point in Pune city, perfect for morning walks.",
    distance: "Calculating...",
  },
  {
    name: "Pashan Lake",
    emoji: "🦢",
    category: "Nature",
    rating: 4.3,
    latitude: 18.539,
    longitude: 73.791,
    entryFee: "Free",
    estYear: "—",
    visitTime: "1.5h",
    hours: "6:00 AM – 7:00 PM",
    phone: "—",
    address: "Pashan",
    accessible: true,
    guidedTours: false,
    tag: "Bird Watching",
    tagColor: "sage",
    bgColor: "#EBF0E8",
    description: "Artificial lake attracting migratory birds in winter.",
    distance: "Calculating...",
  },
  {
    name: "Rajiv Gandhi Zoo",
    emoji: "🦁",
    category: "Nature",
    rating: 4.4,
    latitude: 18.4552,
    longitude: 73.8642,
    entryFee: "₹40",
    estYear: "1999",
    visitTime: "3h",
    hours: "9:30 AM – 5:00 PM",
    phone: "020 2421 1618",
    address: "Katraj",
    accessible: true,
    guidedTours: false,
    tag: "Family",
    tagColor: "sage",
    bgColor: "#EBF0E8",
    description: "Large zoo with a snake park and rescue center.",
    distance: "Calculating...",
  },
  {
    name: "Pu La Deshpande Garden",
    emoji: "🎍",
    category: "Nature",
    rating: 4.6,
    latitude: 18.494,
    longitude: 73.834,
    entryFee: "₹10",
    estYear: "2002",
    visitTime: "1.5h",
    hours: "6:00 AM – 10:00 AM, 4:00 PM – 8:00 PM",
    phone: "—",
    address: "Sinhagad Road",
    accessible: true,
    guidedTours: false,
    tag: "Japanese Garden",
    tagColor: "sage",
    bgColor: "#EBF0E8",
    description: "Authentic Japanese garden inspired by Okayama's Korakuen.",
    distance: "Calculating...",
  },
  {
    name: "Empress Garden",
    emoji: "🌳",
    category: "Nature",
    rating: 4.4,
    latitude: 18.513,
    longitude: 73.896,
    entryFee: "₹20",
    estYear: "1838",
    visitTime: "1.5h",
    hours: "9:30 AM – 6:30 PM",
    phone: "—",
    address: "Kavade Mala",
    accessible: true,
    guidedTours: false,
    tag: "Botanical",
    tagColor: "sage",
    bgColor: "#EBF0E8",
    description: "Historical botanical garden with rare plant species.",
    distance: "Calculating...",
  },
  {
    name: "Khadakwasla Dam",
    emoji: "🌊",
    category: "Nature",
    rating: 4.5,
    latitude: 18.441,
    longitude: 73.763,
    entryFee: "Free",
    estYear: "1879",
    visitTime: "2h",
    hours: "Always open",
    phone: "—",
    address: "Sinhagad Road",
    accessible: true,
    guidedTours: false,
    tag: "Hangout",
    tagColor: "sage",
    bgColor: "#EBF0E8",
    description: "The primary source of water for Pune, a popular evening spot.",
    distance: "Calculating...",
  },
  {
    name: "Sinhagad Fort (Nature)",
    emoji: "🚩",
    category: "Nature",
    rating: 4.8,
    latitude: 18.366,
    longitude: 73.755,
    entryFee: "₹50 (Vehicle)",
    estYear: "Ancient",
    visitTime: "Half Day",
    hours: "5:00 AM – 6:00 PM",
    phone: "—",
    address: "Donje",
    accessible: false,
    guidedTours: false,
    tag: "Adventure",
    tagColor: "sage",
    bgColor: "#EBF0E8",
    description: "Historic hill fort offering a challenging trek and great views.",
    distance: "Calculating...",
  },
  {
    name: "Osho Teerth Park",
    emoji: "🌿",
    category: "Nature",
    rating: 4.5,
    latitude: 18.541,
    longitude: 73.888,
    entryFee: "Free",
    estYear: "1989",
    visitTime: "1h",
    hours: "6:00 AM – 9:00 AM, 3:00 PM – 6:00 PM",
    phone: "—",
    address: "Koregaon Park",
    accessible: true,
    guidedTours: false,
    tag: "Peaceful",
    tagColor: "sage",
    bgColor: "#EBF0E8",
    description: "A beautiful wasteland-turned-forest created by Osho Foundation.",
    distance: "Calculating...",
  },
  {
    name: "Mulshi Dam",
    emoji: "🛶",
    category: "Nature",
    rating: 4.6,
    latitude: 18.486,
    longitude: 73.491,
    entryFee: "Free",
    estYear: "1927",
    visitTime: "Full Day",
    hours: "Always open",
    phone: "—",
    address: "Mulshi",
    accessible: true,
    guidedTours: false,
    tag: "Day Trip",
    tagColor: "sage",
    bgColor: "#EBF0E8",
    description: "Beautiful dam surrounded by Sahyadri hills.",
    distance: "Calculating...",
  },
  {
    name: "Vetal Hill Quarry",
    emoji: "💎",
    category: "Nature",
    rating: 4.4,
    latitude: 18.525,
    longitude: 73.821,
    entryFee: "Free",
    estYear: "—",
    visitTime: "1h",
    hours: "Always open",
    phone: "—",
    address: "Vetal Tekdi",
    accessible: false,
    guidedTours: false,
    tag: "Scenic",
    tagColor: "sage",
    bgColor: "#EBF0E8",
    description: "A hidden quarry within Vetal Tekdi filled with turquoise water.",
    distance: "Calculating...",
  },

  // ── FOOD (10) ──────────────────────────────────────────
  {
    name: "Vaishali Restaurant",
    emoji: "🥯",
    category: "Food",
    rating: 4.7,
    latitude: 18.5234,
    longitude: 73.8415,
    entryFee: "—",
    estYear: "1951",
    visitTime: "1h",
    hours: "7:00 AM – 11:00 PM",
    phone: "020 2553 1244",
    address: "FC Road",
    accessible: true,
    guidedTours: false,
    tag: "Legendary",
    tagColor: "green",
    bgColor: "#FDF3E0",
    description: "Pune's most famous South Indian breakfast spot.",
    distance: "Calculating...",
  },
  {
    name: "Goodluck Cafe",
    emoji: "☕",
    category: "Food",
    rating: 4.5,
    latitude: 18.524,
    longitude: 73.84,
    entryFee: "—",
    estYear: "1935",
    visitTime: "45 min",
    hours: "7:30 AM – 11:30 PM",
    phone: "020 2553 6859",
    address: "FC Road",
    accessible: true,
    guidedTours: false,
    tag: "Irani Cafe",
    tagColor: "green",
    bgColor: "#FDF3E0",
    description: "Famous for Bun Maska, Omelette, and Chai.",
    distance: "Calculating...",
  },
  {
    name: "Kayani Bakery",
    emoji: "🍞",
    category: "Food",
    rating: 4.8,
    latitude: 18.5135,
    longitude: 73.878,
    entryFee: "—",
    estYear: "1955",
    visitTime: "20 min",
    hours: "7:30 AM – 1:00 PM, 3:30 PM – 8:00 PM",
    phone: "020 2636 0517",
    address: "East Street",
    accessible: true,
    guidedTours: false,
    tag: "Biscuits",
    tagColor: "green",
    bgColor: "#FDF3E0",
    description: "The iconic bakery famous for Shrewsbury biscuits.",
    distance: "Calculating...",
  },
  {
    name: "Bedekar Misal",
    emoji: "🍛",
    category: "Food",
    rating: 4.6,
    latitude: 18.515,
    longitude: 73.85,
    entryFee: "—",
    estYear: "1948",
    visitTime: "30 min",
    hours: "8:00 AM – 2:00 PM",
    phone: "—",
    address: "Shaniwar Peth",
    accessible: true,
    guidedTours: false,
    tag: "Misal Pav",
    tagColor: "green",
    bgColor: "#FDF3E0",
    description: "Traditional Puneri Misal with a spicy kick.",
    distance: "Calculating...",
  },
  {
    name: "Sujata Mastani",
    emoji: "🍦",
    category: "Food",
    rating: 4.7,
    latitude: 18.51,
    longitude: 73.855,
    entryFee: "—",
    estYear: "1968",
    visitTime: "20 min",
    hours: "11:00 AM – 11:00 PM",
    phone: "—",
    address: "Sadashiv Peth",
    accessible: true,
    guidedTours: false,
    tag: "Desert",
    tagColor: "green",
    bgColor: "#FDF3E0",
    description: "Famous for 'Mastani', a thick milk shake with ice cream.",
    distance: "Calculating...",
  },
  {
    name: "Blue Nile",
    emoji: "🍖",
    category: "Food",
    rating: 4.4,
    latitude: 18.52,
    longitude: 73.87,
    entryFee: "—",
    estYear: "1970",
    visitTime: "1.5h",
    hours: "11:30 AM – 11:30 PM",
    phone: "—",
    address: "Camp",
    accessible: true,
    guidedTours: false,
    tag: "Biryani",
    tagColor: "green",
    bgColor: "#FDF3E0",
    description: "One of the best places for authentic Biryani and kebabs.",
    distance: "Calculating...",
  },
  {
    name: "Durvankur Thali",
    emoji: "🍱",
    category: "Food",
    rating: 4.5,
    latitude: 18.511,
    longitude: 73.85,
    entryFee: "—",
    estYear: "—",
    visitTime: "1h",
    hours: "12:00 PM – 3:30 PM, 7:00 PM – 10:30 PM",
    phone: "—",
    address: "Sadashiv Peth",
    accessible: true,
    guidedTours: false,
    tag: "Thali",
    tagColor: "green",
    bgColor: "#FDF3E0",
    description: "Traditional Maharashtrian Thali experience.",
    distance: "Calculating...",
  },
  {
    name: "Shabree",
    emoji: "🥘",
    category: "Food",
    rating: 4.6,
    latitude: 18.52,
    longitude: 73.84,
    entryFee: "—",
    estYear: "—",
    visitTime: "1h",
    hours: "12:00 PM – 3:30 PM, 7:30 PM – 11:00 PM",
    phone: "—",
    address: "FC Road",
    accessible: true,
    guidedTours: false,
    tag: "Traditional",
    tagColor: "green",
    bgColor: "#FDF3E0",
    description: "Authentic Maharashtrian cuisine in a classic setting.",
    distance: "Calculating...",
  },
  {
    name: "Chitale Bandhu",
    emoji: "🍬",
    category: "Food",
    rating: 4.9,
    latitude: 18.514,
    longitude: 73.851,
    entryFee: "—",
    estYear: "1950",
    visitTime: "15 min",
    hours: "9:00 AM – 8:30 PM",
    phone: "—",
    address: "Shaniwar Peth",
    accessible: true,
    guidedTours: false,
    tag: "Bakarwadi",
    tagColor: "green",
    bgColor: "#FDF3E0",
    description: "World famous for Bakarwadi and traditional sweets.",
    distance: "Calculating...",
  },
  {
    name: "German Bakery",
    emoji: "🍰",
    category: "Food",
    rating: 4.4,
    latitude: 18.538,
    longitude: 73.888,
    entryFee: "—",
    estYear: "1988",
    visitTime: "1h",
    hours: "8:00 AM – 11:30 PM",
    phone: "—",
    address: "Koregaon Park",
    accessible: true,
    guidedTours: false,
    tag: "Backpackers",
    tagColor: "green",
    bgColor: "#FDF3E0",
    description: "A cultural landmark in Pune, famous for its cakes and atmosphere.",
    distance: "Calculating...",
  },
];

const events = [
  {
    date: "SAT · JUN 14",
    name: "Sawai Gandharva Festival",
    desc: "Classical music at Balgandharva Rang",
    color: "terracotta",
  },
  {
    date: "SUN · JUN 15",
    name: "Pune Food Walk",
    desc: "FC Road street eats tour",
    color: "indigo",
  },
  {
    date: "WED · JUN 18",
    name: "Osho Meditation Session",
    desc: "Evening zen at Koregaon Park",
    color: "terracotta",
  },
  {
    date: "FRI · JUN 20",
    name: "Pune Tech Meetup",
    desc: "Networking at Hinjewadi IT Park",
    color: "indigo",
  },
  {
    date: "SAT · JUN 21",
    name: "Heritage Cycle Tour",
    desc: "Morning ride through old city",
    color: "terracotta",
  },
];

const itineraryDays = [
  {
    day: 1,
    label: "Day 1 · Sat",
    stops: [
      {
        time: "9 AM",
        name: "Shaniwar Wada",
        desc: "Start with the Peshwa fortress — arrive early to beat the crowds and catch the morning light on the Dilli Darwaza gate.",
        tags: [{ label: "Heritage", type: "heritage" }, { label: "1.5h", type: "neutral" }],
        dotColor: "#8B3A2A",
      },
      {
        time: "11 AM",
        name: "Dagdusheth Halwai Ganpati",
        desc: "Walk 10 min to the iconic Ganesh temple. Don't miss the modak prasad offered at the temple entrance.",
        tags: [{ label: "Temple", type: "heritage" }, { label: "45 min", type: "neutral" }],
        dotColor: "#B87318",
      },
      {
        time: "12:30",
        name: "Lunch — Vaishali Restaurant",
        desc: "Iconic Puneri thali on FC Road. Try the missal pav and ukdiche modak — a Pune institution since 1972.",
        tags: [{ label: "Food", type: "food" }, { label: "1h", type: "neutral" }],
        dotColor: "#B87318",
      },
      {
        time: "2 PM",
        name: "Aga Khan Palace",
        desc: "Site of Mahatma Gandhi's internment — a poignant colonial-era landmark set in serene gardens.",
        tags: [{ label: "Heritage", type: "heritage" }, { label: "Gardens", type: "nature" }, { label: "1.5h", type: "neutral" }],
        dotColor: "#4A6741",
      },
      {
        time: "4 PM",
        name: "Evening chai — Irani Café",
        desc: "End Day 1 with cutting chai and Osmania biscuits at a Pune Irani café. Bund Garden Road has the best ones.",
        tags: [{ label: "Food", type: "food" }],
        dotColor: "#3D3680",
      },
    ],
  },
  {
    day: 2,
    label: "Day 2 · Sun",
    stops: [
      {
        time: "8 AM",
        name: "Sinhagad Fort Trek",
        desc: "Early morning trek up the historic Sinhagad fort — cool air, sweeping views, and freshly made pitla bhakri at the top.",
        tags: [{ label: "Heritage", type: "heritage" }, { label: "Nature", type: "nature" }, { label: "3h", type: "neutral" }],
        dotColor: "#8B3A2A",
      },
      {
        time: "12 PM",
        name: "Parvati Hill & Temple",
        desc: "Climb 103 steps to the Parvati temple overlooking Pune city — the best panoramic viewpoint in the city.",
        tags: [{ label: "Temple", type: "heritage" }, { label: "1h", type: "neutral" }],
        dotColor: "#B87318",
      },
      {
        time: "2 PM",
        name: "Pune Museum (Raja Kelkar)",
        desc: "One of India's most eclectic private collections — over 20,000 artefacts including lamps, locks, and miniature paintings.",
        tags: [{ label: "Heritage", type: "heritage" }, { label: "1.5h", type: "neutral" }],
        dotColor: "#4A6741",
      },
      {
        time: "5 PM",
        name: "Osho Ashram Walk",
        desc: "Stroll the shaded lanes of Koregaon Park around the Ashram, ending at a rooftop café for sunset views.",
        tags: [{ label: "Wellness", type: "nature" }, { label: "1h", type: "neutral" }],
        dotColor: "#3D3680",
      },
    ],
  },
];

async function main() {
  console.log('Start seeding...');

  // Clear existing data
  await prisma.itineraryStop.deleteMany();
  await prisma.itineraryDay.deleteMany();
  await prisma.event.deleteMany();
  await prisma.place.deleteMany();

  // Seed Places
  for (const p of places) {
    await prisma.place.create({ data: p as any });
  }

  // Seed Events
  for (const e of events) {
    await prisma.event.create({ data: e });
  }

  // Seed Itineraries
  for (const day of itineraryDays) {
    const createdDay = await prisma.itineraryDay.create({
      data: {
        day: day.day,
        label: day.label,
      },
    });

    for (const stop of day.stops) {
      await prisma.itineraryStop.create({
        data: {
          time: stop.time,
          name: stop.name,
          desc: stop.desc,
          dotColor: stop.dotColor,
          itineraryDayId: createdDay.id,
          tags: stop.tags as any,
        },
      });
    }
  }

  console.log('Seeding finished.');
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
